
export default {
  CONNECT_MISSING: Symbol('SOCKETS/CONNECT_MISSING'),
  CONNECT_REQUEST: Symbol('SOCKETS/CONNECT_REQUEST'),
  CONNECT_FAILURE: Symbol('SOCKETS/CONNECT_FAILURE'),
  CONNECT_SUCCESS: Symbol('SOCKETS/CONNECT_SUCCESS'),
  BORD_MOUNT:      Symbol('SOCKETS/BORD_MOUNT'),
  BORD_UNMOUNT:    Symbol('SOCKETS/BORD_UNMOUNT'),
  CARD_CREATE:     Symbol('SOCKETS/CARD_CREATE'),
  CARD_UPDATE:     Symbol('SOCKETS/CARD_UPDATE'),
  CARD_REMOVE:     Symbol('SOCKETS/CARD_REMOVE'),
  COLUMN_CREATE:   Symbol('SOCKETS/COLUMN_CREATE'),
  COLUMN_UPDATE:   Symbol('SOCKETS/COLUMN_UPDATE'),
  COLUMN_REMOVE:   Symbol('SOCKETS/COLUMN_REMOVE')
}
